"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os
import dotenv
from celery.schedules import crontab

dotenv.load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# This uses an environment variable. Learn how to set it up using the README installation.
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
TRANSLINK_API_KEY = os.getenv('TRANSLINK_API_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('TRANSIT_ALLOWED_HOSTS', 'localhost 127.0.0.1').split(' ')


# Application definition

CORS_ORIGIN_ALLOW_ALL = False
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = ["http://localhost:3000", 'http://127.0.0.1:3000']

# CORS_ALLOW_HEADERS = (
#     "accept",
#     "authorization",
#     "content-type",
#     "user-agent",
#     "x-csrftoken",
#     "x-requested-with",
# )

CSRF_TRUSTED_ORIGINS = ["http://localhost:3000", "http://127.0.0.1:3000",]

CORS_EXPOSE_HEADERS = ["Content-Type", "X-CSRFToken"]
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTP_ONLY = True
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_SAMESITE = 'Lax'

# Celery configuration

CELERY_BROKER_URL = "redis://redis:6379"
CELERY_RESULT_BACKEND = "redis://redis:6379"
CELERY_TIMEZONE = "America/Vancouver"
CELERY_IMPORTS = "core.cron"

INSTALLED_APPS = [
    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Our apps
    'core',

    # Third-party apps
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist',
    'django_cron'
]

REST_FRAMEWORK = {
     'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
      ],
    'DEFAULT_THROTTLE_CLASSES': [
        'core.throttling.BurstAnonRateThrottle',
        'core.throttling.SustainedAnonRateThrottle',
        'core.throttling.BurstUserRateThrottle',
        'core.throttling.SustainedUserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon_burst': '20/min',
        'anon_sustained': '200/day',
        'user_burst': '60/min',
        'user_sustained': '2000/day',
        'password_reset_request': '2/min'
    }
}


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

SIMPLE_JWT = {
     'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
     'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
     'ROTATE_REFRESH_TOKENS': True,
     'BLACKLIST_AFTER_ROTATION': True
}

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

db_pw = os.getenv("TRANSIT_DB_PASSWORD")
db_name = os.getenv("TRANSIT_DB_NAME")
db_user = os.getenv("TRANSIT_DB_USER")
db_host = os.getenv("TRANSIT_DB_HOST")
db_port = os.getenv("TRANSIT_DB_PORT")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": db_name,
        'USER': db_user,
        'PASSWORD': db_pw,
        'HOST': db_host,
        'PORT': db_port,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Email Settings

EMAIL_HOST = os.getenv("TRANSIT_EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("TRANSIT_EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("TRANSIT_EMAIL_USE_TLS", "true") == "true"
EMAIL_USE_SSL = not os.getenv("TRANSIT_EMAIL_USE_SSL", "false") == "false"

EMAIL_HOST_USER = os.getenv("TRANSIT_EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("TRANSIT_EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("TRANSIT_DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = 'core.User'

# Logging settings
# TODO: Change levels from DEBUG to WARNING for production
# https://docs.djangoproject.com/en/5.1/topics/logging/
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'core': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# # Django cron
# # This registers the cron job
# CRON_CLASSES = [
#     'core.cron.SyncCoursesCronJob',
# ]

# This registers the cron jobs for Celery to execute
CELERY_BEAT_SCHEDULE = {
    "update_course_data": {
        "task": "core.cron.update_course_data",
        "schedule": crontab(hour=0, minute=0, day_of_month='1', month_of_year='1,5,9')  # Every 4 months (Jan, May, Sept)
    },
    "remove_blacklisted_tokens": {
        "task": "core.cron.remove_blacklisted_tokens",
        "schedule": crontab(minute=0, hour=0)  # Once a day at midnight
    }
}


# Production Security Settings
if not DEBUG: 
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
