# Generated by Django 4.2.25 on 2025-11-03 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='class_number',
        ),
        migrations.RemoveField(
            model_name='course',
            name='delivery_method',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='section_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='term',
        ),
        migrations.RemoveField(
            model_name='lecturesection',
            name='days',
        ),
        migrations.RemoveField(
            model_name='lecturesection',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='lecturesection',
            name='is_exam',
        ),
        migrations.RemoveField(
            model_name='lecturesection',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='nonlecturesection',
            name='days',
        ),
        migrations.RemoveField(
            model_name='nonlecturesection',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='nonlecturesection',
            name='is_exam',
        ),
        migrations.RemoveField(
            model_name='nonlecturesection',
            name='start_time',
        ),
        migrations.AddField(
            model_name='lecturesection',
            name='delivery_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lecturesection',
            name='schedule',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonlecturesection',
            name='schedule',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_number',
            field=models.CharField(default='000', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(db_index=True, default='Untitled', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='lecturesection',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_sections', to='core.course'),
        ),
        migrations.AlterField(
            model_name='lecturesection',
            name='title',
            field=models.CharField(db_index=True, default='Untitled', max_length=100, unique=True),
        ),
    ]
