# Generated by Django 5.0.6 on 2024-07-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='section_name',
            field=models.CharField(default='D100', max_length=100),
        ),
    ]
