# Generated by Django 4.2.25 on 2025-11-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_course_class_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(db_index=True, default='Untitled', max_length=100),
        ),
        migrations.AlterField(
            model_name='lecturesection',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]

