# Generated by Django 4.2.25 on 2025-11-11 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_course_title_alter_lecturesection_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Courses',
            new_name='courses',
        ),
    ]
