# Generated by Django 5.0.6 on 2025-12-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_courses_user_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='courses',
        ),
        migrations.AddField(
            model_name='user',
            name='lecture_sections',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.lecturesection'),
        ),
        migrations.AddField(
            model_name='user',
            name='non_lecture_sections',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.nonlecturesection'),
        ),
    ]
