# Generated by Django 5.0.6 on 2025-12-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_courses_user_lecture_sections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturesection',
            name='department',
            field=models.CharField(default='No department', max_length=100),
        ),
        migrations.AddField(
            model_name='nonlecturesection',
            name='department',
            field=models.CharField(default='No department', max_length=100),
        ),
    ]
