# Generated by Django 5.0.6 on 2025-12-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_lecturesection_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturesection',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturesection',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonlecturesection',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonlecturesection',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
