# Generated by Django 5.0.6 on 2025-12-28 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_lecturesection_end_time_lecturesection_start_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSemesterNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('term', models.CharField(choices=[('1', 'Spring'), ('2', 'Summer'), ('3', 'Fall')], default=None, max_length=6, null=True)),
                ('year', models.IntegerField()),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_semester_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
