# Generated by Django 5.0.6 on 2026-02-19 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_user_otp_remove_user_otp_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default='Untitled', max_length=100)),
                ('name', models.CharField(db_index=True, default='Untitled', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.department'),
        ),
    ]
